builders:
  error_mapper_builder:
    import: "package:bloc_error_control_generator/bloc_error_control_generator.dart"
    builder_factories: ["errorMapperBuilder"]
    build_extensions: {".dart": [".error.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]