targets:
  $default:
    builders:
      bloc_error_control_generator|error_mapper_builder:
        enabled: true
        generate_for:
          include:
            - "lib/bloc/*_bloc.dart"
          exclude:
            - "lib/**/*.g.dart"