name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bloc_error_control:
    path: ../../bloc_error_control/
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

  # Твое ядро

dev_dependencies:
  bloc_error_control_generator:
    path: ../../bloc_error_control_generator/
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
